// Code generated by aliaspkg. DO NOT EDIT.

package log

import (
	"log"
)

// This is an alias of https://pkg.go.dev/log#Print.
func Print(v ...any) {
	log.Print(v...)
}

// This is an alias of https://pkg.go.dev/log#Printf.
func Printf(format string, v ...any) {
	log.Printf(format, v...)
}

// This is an alias of https://pkg.go.dev/log#Println.
func Println(v ...any) {
	log.Println(v...)
}

// This is an alias of https://pkg.go.dev/log#Fatal.
func Fatal(v ...any) {
	log.Fatal(v...)
}

// This is an alias of https://pkg.go.dev/log#Fatalf.
func Fatalf(format string, v ...any) {
	log.Fatalf(format, v...)
}

// This is an alias of https://pkg.go.dev/log#Fatalln.
func Fatalln(v ...any) {
	log.Fatalln(v...)
}

// This is an alias of https://pkg.go.dev/log#Panic.
func Panic(v ...any) {
	log.Panic(v...)
}

// This is an alias of https://pkg.go.dev/log#Panicf.
func Panicf(format string, v ...any) {
	log.Panicf(format, v...)
}

// This is an alias of https://pkg.go.dev/log#Panicln.
func Panicln(v ...any) {
	log.Panicln(v...)
}
