// Code generated by aliaspkg. DO NOT EDIT.

package maps

// Package maps defines various functions useful with maps of any type.
//
// This package does not have any special handling for non-reflexive keys
// (keys k where k != k), such as floating-point NaNs.

import (
	"iter"
	"maps"
)

// All returns an iterator over key-value pairs from m.
// The iteration order is not specified and is not guaranteed
// to be the same from one call to the next.
//
// This is an alias of https://pkg.go.dev/maps#All.
func All[Map ~map[K]V, K comparable, V any](m Map) iter.Seq2[K, V] {
	return maps.All[Map, K, V](m)
}

// Keys returns an iterator over keys in m.
// The iteration order is not specified and is not guaranteed
// to be the same from one call to the next.
//
// This is an alias of https://pkg.go.dev/maps#Keys.
func Keys[Map ~map[K]V, K comparable, V any](m Map) iter.Seq[K] {
	return maps.Keys[Map, K, V](m)
}

// Values returns an iterator over values in m.
// The iteration order is not specified and is not guaranteed
// to be the same from one call to the next.
//
// This is an alias of https://pkg.go.dev/maps#Values.
func Values[Map ~map[K]V, K comparable, V any](m Map) iter.Seq[V] {
	return maps.Values[Map, K, V](m)
}

// Insert adds the key-value pairs from seq to m.
// If a key in seq already exists in m, its value will be overwritten.
//
// This is an alias of https://pkg.go.dev/maps#Insert.
func Insert[Map ~map[K]V, K comparable, V any](m Map, seq iter.Seq2[K, V]) {
	maps.Insert[Map, K, V](m, seq)
}

// Collect collects key-value pairs from seq into a new map
// and returns it.
//
// This is an alias of https://pkg.go.dev/maps#Collect.
func Collect[K comparable, V any](seq iter.Seq2[K, V]) map[K]V {
	return maps.Collect[K, V](seq)
}

// Equal reports whether two maps contain the same key/value pairs.
// Values are compared using ==.
//
// This is an alias of https://pkg.go.dev/maps#Equal.
func Equal[M1, M2 ~map[K]V, K, V comparable](m1 M1, m2 M2) bool {
	return maps.Equal[M1, M2, K, V](m1, m2)
}

// EqualFunc is like Equal, but compares values using eq.
// Keys are still compared with ==.
//
// This is an alias of https://pkg.go.dev/maps#EqualFunc.
func EqualFunc[M1 ~map[K]V1, M2 ~map[K]V2, K comparable, V1, V2 any](m1 M1, m2 M2, eq func(V1, V2) bool) bool {
	return maps.EqualFunc[M1, M2, K, V1, V2](m1, m2, eq)
}

// Clone returns a copy of m.  This is a shallow clone:
// the new keys and values are set using ordinary assignment.
//
// This is an alias of https://pkg.go.dev/maps#Clone.
func Clone[M ~map[K]V, K comparable, V any](m M) M {
	return maps.Clone[M, K, V](m)
}

// Copy copies all key/value pairs in src adding them to dst.
// When a key in src is already present in dst,
// the value in dst will be overwritten by the value associated
// with the key in src.
//
// This is an alias of https://pkg.go.dev/maps#Copy.
func Copy[M1 ~map[K]V, M2 ~map[K]V, K comparable, V any](dst M1, src M2) {
	maps.Copy[M1, M2, K, V](dst, src)
}

// DeleteFunc deletes any key/value pairs from m for which del returns true.
//
// This is an alias of https://pkg.go.dev/maps#DeleteFunc.
func DeleteFunc[M ~map[K]V, K comparable, V any](m M, del func(K, V) bool) {
	maps.DeleteFunc[M, K, V](m, del)
}
