// Code generated by aliaspkg. DO NOT EDIT.

package slog

/*
Package slog provides structured logging,
in which log records include a message,
a severity level, and various other attributes
expressed as key-value pairs.

It defines a type, [Logger],
which provides several methods (such as [Logger.Info] and [Logger.Error])
for reporting events of interest.

Each Logger is associated with a [Handler].
A Logger output method creates a [Record] from the method arguments
and passes it to the Handler, which decides how to handle it.
There is a default Logger accessible through top-level functions
(such as [Info] and [Error]) that call the corresponding Logger methods.

A log record consists of a time, a level, a message, and a set of key-value
pairs, where the keys are strings and the values may be of any type.
As an example,

	slog.Info("hello", "count", 3)

creates a record containing the time of the call,
a level of Info, the message "hello", and a single
pair with key "count" and value 3.

The [Info] top-level function calls the [Logger.Info] method on the default Logger.
In addition to [Logger.Info], there are methods for Debug, Warn and Error levels.
Besides these convenience methods for common levels,
there is also a [Logger.Log] method which takes the level as an argument.
Each of these methods has a corresponding top-level function that uses the
default logger.

The default handler formats the log record's message, time, level, and attributes
as a string and passes it to the [log] package.

	2022/11/08 15:28:26 INFO hello count=3

For more control over the output format, create a logger with a different handler.
This statement uses [New] to create a new logger with a [TextHandler]
that writes structured records in text form to standard error:

	logger := slog.New(slog.NewTextHandler(os.Stderr, nil))

[TextHandler] output is a sequence of key=value pairs, easily and unambiguously
parsed by machine. This statement:

	logger.Info("hello", "count", 3)

produces this output:

	time=2022-11-08T15:28:26.000-05:00 level=INFO msg=hello count=3

The package also provides [JSONHandler], whose output is line-delimited JSON:

	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))
	logger.Info("hello", "count", 3)

produces this output:

	{"time":"2022-11-08T15:28:26.000000000-05:00","level":"INFO","msg":"hello","count":3}

Both [TextHandler] and [JSONHandler] can be configured with [HandlerOptions].
There are options for setting the minimum level (see Levels, below),
displaying the source file and line of the log call, and
modifying attributes before they are logged.

Setting a logger as the default with

	slog.SetDefault(logger)

will cause the top-level functions like [Info] to use it.
[SetDefault] also updates the default logger used by the [log] package,
so that existing applications that use [log.Printf] and related functions
will send log records to the logger's handler without needing to be rewritten.

Some attributes are common to many log calls.
For example, you may wish to include the URL or trace identifier of a server request
with all log events arising from the request.
Rather than repeat the attribute with every log call, you can use [Logger.With]
to construct a new Logger containing the attributes:

	logger2 := logger.With("url", r.URL)

The arguments to With are the same key-value pairs used in [Logger.Info].
The result is a new Logger with the same handler as the original, but additional
attributes that will appear in the output of every call.

# Levels

A [Level] is an integer representing the importance or severity of a log event.
The higher the level, the more severe the event.
This package defines constants for the most common levels,
but any int can be used as a level.

In an application, you may wish to log messages only at a certain level or greater.
One common configuration is to log messages at Info or higher levels,
suppressing debug logging until it is needed.
The built-in handlers can be configured with the minimum level to output by
setting [HandlerOptions.Level].
The program's `main` function typically does this.
The default value is LevelInfo.

Setting the [HandlerOptions.Level] field to a [Level] value
fixes the handler's minimum level throughout its lifetime.
Setting it to a [LevelVar] allows the level to be varied dynamically.
A LevelVar holds a Level and is safe to read or write from multiple
goroutines.
To vary the level dynamically for an entire program, first initialize
a global LevelVar:

	var programLevel = new(slog.LevelVar) // Info by default

Then use the LevelVar to construct a handler, and make it the default:

	h := slog.NewJSONHandler(os.Stderr, &slog.HandlerOptions{Level: programLevel})
	slog.SetDefault(slog.New(h))

Now the program can change its logging level with a single statement:

	programLevel.Set(slog.LevelDebug)

# Groups

Attributes can be collected into groups.
A group has a name that is used to qualify the names of its attributes.
How this qualification is displayed depends on the handler.
[TextHandler] separates the group and attribute names with a dot.
[JSONHandler] treats each group as a separate JSON object, with the group name as the key.

Use [Group] to create a Group attribute from a name and a list of key-value pairs:

	slog.Group("request",
	    "method", r.Method,
	    "url", r.URL)

TextHandler would display this group as

	request.method=GET request.url=http://example.com

JSONHandler would display it as

	"request":{"method":"GET","url":"http://example.com"}

Use [Logger.WithGroup] to qualify all of a Logger's output
with a group name. Calling WithGroup on a Logger results in a
new Logger with the same Handler as the original, but with all
its attributes qualified by the group name.

This can help prevent duplicate attribute keys in large systems,
where subsystems might use the same keys.
Pass each subsystem a different Logger with its own group name so that
potential duplicates are qualified:

	logger := slog.Default().With("id", systemID)
	parserLogger := logger.WithGroup("parser")
	parseInput(input, parserLogger)

When parseInput logs with parserLogger, its keys will be qualified with "parser",
so even if it uses the common key "id", the log line will have distinct keys.

# Contexts

Some handlers may wish to include information from the [context.Context] that is
available at the call site. One example of such information
is the identifier for the current span when tracing is enabled.

The [Logger.Log] and [Logger.LogAttrs] methods take a context as a first
argument, as do their corresponding top-level functions.

Although the convenience methods on Logger (Info and so on) and the
corresponding top-level functions do not take a context, the alternatives ending
in "Context" do. For example,

	slog.InfoContext(ctx, "message")

It is recommended to pass a context to an output method if one is available.

# Attrs and Values

An [Attr] is a key-value pair. The Logger output methods accept Attrs as well as
alternating keys and values. The statement

	slog.Info("hello", slog.Int("count", 3))

behaves the same as

	slog.Info("hello", "count", 3)

There are convenience constructors for [Attr] such as [Int], [String], and [Bool]
for common types, as well as the function [Any] for constructing Attrs of any
type.

The value part of an Attr is a type called [Value].
Like an [any], a Value can hold any Go value,
but it can represent typical values, including all numbers and strings,
without an allocation.

For the most efficient log output, use [Logger.LogAttrs].
It is similar to [Logger.Log] but accepts only Attrs, not alternating
keys and values; this allows it, too, to avoid allocation.

The call

	logger.LogAttrs(ctx, slog.LevelInfo, "hello", slog.Int("count", 3))

is the most efficient way to achieve the same output as

	slog.InfoContext(ctx, "hello", "count", 3)

# Customizing a type's logging behavior

If a type implements the [LogValuer] interface, the [Value] returned from its LogValue
method is used for logging. You can use this to control how values of the type
appear in logs. For example, you can redact secret information like passwords,
or gather a struct's fields in a Group. See the examples under [LogValuer] for
details.

A LogValue method may return a Value that itself implements [LogValuer]. The [Value.Resolve]
method handles these cases carefully, avoiding infinite loops and unbounded recursion.
Handler authors and others may wish to use [Value.Resolve] instead of calling LogValue directly.

# Wrapping output methods

The logger functions use reflection over the call stack to find the file name
and line number of the logging call within the application. This can produce
incorrect source information for functions that wrap slog. For instance, if you
define this function in file mylog.go:

	func Infof(logger *slog.Logger, format string, args ...any) {
	    logger.Info(fmt.Sprintf(format, args...))
	}

and you call it like this in main.go:

	Infof(slog.Default(), "hello, %s", "world")

then slog will report the source file as mylog.go, not main.go.

A correct implementation of Infof will obtain the source location
(pc) and pass it to NewRecord.
The Infof function in the package-level example called "wrapping"
demonstrates how to do this.

# Working with Records

Sometimes a Handler will need to modify a Record
before passing it on to another Handler or backend.
A Record contains a mixture of simple public fields (e.g. Time, Level, Message)
and hidden fields that refer to state (such as attributes) indirectly. This
means that modifying a simple copy of a Record (e.g. by calling
[Record.Add] or [Record.AddAttrs] to add attributes)
may have unexpected effects on the original.
Before modifying a Record, use [Record.Clone] to
create a copy that shares no state with the original,
or create a new Record with [NewRecord]
and build up its Attrs by traversing the old ones with [Record.Attrs].

# Performance considerations

If profiling your application demonstrates that logging is taking significant time,
the following suggestions may help.

If many log lines have a common attribute, use [Logger.With] to create a Logger with
that attribute. The built-in handlers will format that attribute only once, at the
call to [Logger.With]. The [Handler] interface is designed to allow that optimization,
and a well-written Handler should take advantage of it.

The arguments to a log call are always evaluated, even if the log event is discarded.
If possible, defer computation so that it happens only if the value is actually logged.
For example, consider the call

	slog.Info("starting request", "url", r.URL.String())  // may compute String unnecessarily

The URL.String method will be called even if the logger discards Info-level events.
Instead, pass the URL directly:

	slog.Info("starting request", "url", &r.URL) // calls URL.String only if needed

The built-in [TextHandler] will call its String method, but only
if the log event is enabled.
Avoiding the call to String also preserves the structure of the underlying value.
For example [JSONHandler] emits the components of the parsed URL as a JSON object.
If you want to avoid eagerly paying the cost of the String call
without causing the handler to potentially inspect the structure of the value,
wrap the value in a fmt.Stringer implementation that hides its Marshal methods.

You can also use the [LogValuer] interface to avoid unnecessary work in disabled log
calls. Say you need to log some expensive value:

	slog.Debug("frobbing", "value", computeExpensiveValue(arg))

Even if this line is disabled, computeExpensiveValue will be called.
To avoid that, define a type implementing LogValuer:

	type expensive struct { arg int }

	func (e expensive) LogValue() slog.Value {
	    return slog.AnyValue(computeExpensiveValue(e.arg))
	}

Then use a value of that type in log calls:

	slog.Debug("frobbing", "value", expensive{arg})

Now computeExpensiveValue will only be called when the line is enabled.

The built-in handlers acquire a lock before calling [io.Writer.Write]
to ensure that exactly one [Record] is written at a time in its entirety.
Although each log record has a timestamp,
the built-in handlers do not use that time to sort the written records.
User-defined handlers are responsible for their own locking and sorting.

# Writing a handler

For a guide to writing a custom handler, see https://golang.org/s/slog-handler-guide.
*/

import (
	"context"
	"io"
	"log"
	"log/slog"
	"time"
)

// TimeKey is the key used by the built-in handlers for the time
// when the log method is called. The associated Value is a [time.Time].
//
// This is an alias of https://pkg.go.dev/log/slog#TimeKey.
const TimeKey = slog.TimeKey

// LevelKey is the key used by the built-in handlers for the level
// of the log call. The associated value is a [Level].
//
// This is an alias of https://pkg.go.dev/log/slog#LevelKey.
const LevelKey = slog.LevelKey

// MessageKey is the key used by the built-in handlers for the
// message of the log call. The associated value is a string.
//
// This is an alias of https://pkg.go.dev/log/slog#MessageKey.
const MessageKey = slog.MessageKey

// SourceKey is the key used by the built-in handlers for the source file
// and line of the log call. The associated value is a *[Source].
//
// This is an alias of https://pkg.go.dev/log/slog#SourceKey.
const SourceKey = slog.SourceKey

// This is an alias of https://pkg.go.dev/log/slog#LevelDebug.
const LevelDebug = slog.LevelDebug

// This is an alias of https://pkg.go.dev/log/slog#LevelInfo.
const LevelInfo = slog.LevelInfo

// This is an alias of https://pkg.go.dev/log/slog#LevelWarn.
const LevelWarn = slog.LevelWarn

// This is an alias of https://pkg.go.dev/log/slog#LevelError.
const LevelError = slog.LevelError

// This is an alias of https://pkg.go.dev/log/slog#KindAny.
const KindAny = slog.KindAny

// This is an alias of https://pkg.go.dev/log/slog#KindBool.
const KindBool = slog.KindBool

// This is an alias of https://pkg.go.dev/log/slog#KindDuration.
const KindDuration = slog.KindDuration

// This is an alias of https://pkg.go.dev/log/slog#KindFloat64.
const KindFloat64 = slog.KindFloat64

// This is an alias of https://pkg.go.dev/log/slog#KindInt64.
const KindInt64 = slog.KindInt64

// This is an alias of https://pkg.go.dev/log/slog#KindString.
const KindString = slog.KindString

// This is an alias of https://pkg.go.dev/log/slog#KindTime.
const KindTime = slog.KindTime

// This is an alias of https://pkg.go.dev/log/slog#KindUint64.
const KindUint64 = slog.KindUint64

// This is an alias of https://pkg.go.dev/log/slog#KindGroup.
const KindGroup = slog.KindGroup

// This is an alias of https://pkg.go.dev/log/slog#KindLogValuer.
const KindLogValuer = slog.KindLogValuer

// This is an alias of https://pkg.go.dev/log/slog#DiscardHandler.
var DiscardHandler = slog.DiscardHandler

// An Attr is a key-value pair.
//
// This is an alias of https://pkg.go.dev/log/slog#Attr.
type Attr = slog.Attr

// A Handler handles log records produced by a Logger.
//
// A typical handler may print log records to standard error,
// or write them to a file or database, or perhaps augment them
// with additional attributes and pass them on to another handler.
//
// Any of the Handler's methods may be called concurrently with itself
// or with other methods. It is the responsibility of the Handler to
// manage this concurrency.
//
// Users of the slog package should not invoke Handler methods directly.
// They should use the methods of [Logger] instead.
//
// Before implementing your own handler, consult https://go.dev/s/slog-handler-guide.
//
// This is an alias of https://pkg.go.dev/log/slog#Handler.
type Handler = slog.Handler

// HandlerOptions are options for a [TextHandler] or [JSONHandler].
// A zero HandlerOptions consists entirely of default values.
//
// This is an alias of https://pkg.go.dev/log/slog#HandlerOptions.
type HandlerOptions = slog.HandlerOptions

// JSONHandler is a [Handler] that writes Records to an [io.Writer] as
// line-delimited JSON objects.
//
// This is an alias of https://pkg.go.dev/log/slog#JSONHandler.
type JSONHandler = slog.JSONHandler

// A Level is the importance or severity of a log event.
// The higher the level, the more important or severe the event.
//
// This is an alias of https://pkg.go.dev/log/slog#Level.
type Level = slog.Level

// A LevelVar is a [Level] variable, to allow a [Handler] level to change
// dynamically.
// It implements [Leveler] as well as a Set method,
// and it is safe for use by multiple goroutines.
// The zero LevelVar corresponds to [LevelInfo].
//
// This is an alias of https://pkg.go.dev/log/slog#LevelVar.
type LevelVar = slog.LevelVar

// A Leveler provides a [Level] value.
//
// As Level itself implements Leveler, clients typically supply
// a Level value wherever a Leveler is needed, such as in [HandlerOptions].
// Clients who need to vary the level dynamically can provide a more complex
// Leveler implementation such as *[LevelVar].
//
// This is an alias of https://pkg.go.dev/log/slog#Leveler.
type Leveler = slog.Leveler

// A Logger records structured information about each call to its
// Log, Debug, Info, Warn, and Error methods.
// For each call, it creates a [Record] and passes it to a [Handler].
//
// To create a new Logger, call [New] or a Logger method
// that begins "With".
//
// This is an alias of https://pkg.go.dev/log/slog#Logger.
type Logger = slog.Logger

// A Record holds information about a log event.
// Copies of a Record share state.
// Do not modify a Record after handing out a copy to it.
// Call [NewRecord] to create a new Record.
// Use [Record.Clone] to create a copy with no shared state.
//
// This is an alias of https://pkg.go.dev/log/slog#Record.
type Record = slog.Record

// Source describes the location of a line of source code.
//
// This is an alias of https://pkg.go.dev/log/slog#Source.
type Source = slog.Source

// TextHandler is a [Handler] that writes Records to an [io.Writer] as a
// sequence of key=value pairs separated by spaces and followed by a newline.
//
// This is an alias of https://pkg.go.dev/log/slog#TextHandler.
type TextHandler = slog.TextHandler

// A Value can represent any Go value, but unlike type any,
// it can represent most small values without an allocation.
// The zero Value corresponds to nil.
//
// This is an alias of https://pkg.go.dev/log/slog#Value.
type Value = slog.Value

// Kind is the kind of a [Value].
//
// This is an alias of https://pkg.go.dev/log/slog#Kind.
type Kind = slog.Kind

// A LogValuer is any Go value that can convert itself into a Value for logging.
//
// This mechanism may be used to defer expensive operations until they are
// needed, or to expand a single value into a sequence of components.
//
// This is an alias of https://pkg.go.dev/log/slog#LogValuer.
type LogValuer = slog.LogValuer

// String returns an Attr for a string value.
//
// This is an alias of https://pkg.go.dev/log/slog#String.
func String(key, value string) Attr {
	return slog.String(key, value)
}

// Int64 returns an Attr for an int64.
//
// This is an alias of https://pkg.go.dev/log/slog#Int64.
func Int64(key string, value int64) Attr {
	return slog.Int64(key, value)
}

// Int converts an int to an int64 and returns
// an Attr with that value.
//
// This is an alias of https://pkg.go.dev/log/slog#Int.
func Int(key string, value int) Attr {
	return slog.Int(key, value)
}

// Uint64 returns an Attr for a uint64.
//
// This is an alias of https://pkg.go.dev/log/slog#Uint64.
func Uint64(key string, v uint64) Attr {
	return slog.Uint64(key, v)
}

// Float64 returns an Attr for a floating-point number.
//
// This is an alias of https://pkg.go.dev/log/slog#Float64.
func Float64(key string, v float64) Attr {
	return slog.Float64(key, v)
}

// Bool returns an Attr for a bool.
//
// This is an alias of https://pkg.go.dev/log/slog#Bool.
func Bool(key string, v bool) Attr {
	return slog.Bool(key, v)
}

// Time returns an Attr for a [time.Time].
// It discards the monotonic portion.
//
// This is an alias of https://pkg.go.dev/log/slog#Time.
func Time(key string, v time.Time) Attr {
	return slog.Time(key, v)
}

// Duration returns an Attr for a [time.Duration].
//
// This is an alias of https://pkg.go.dev/log/slog#Duration.
func Duration(key string, v time.Duration) Attr {
	return slog.Duration(key, v)
}

// Group returns an Attr for a Group [Value].
// The first argument is the key; the remaining arguments
// are converted to Attrs as in [Logger.Log].
//
// Use Group to collect several key-value pairs under a single
// key on a log line, or as the result of LogValue
// in order to log a single value as multiple Attrs.
//
// This is an alias of https://pkg.go.dev/log/slog#Group.
func Group(key string, args ...any) Attr {
	return slog.Group(key, args...)
}

// GroupAttrs returns an Attr for a Group [Value]
// consisting of the given Attrs.
//
// GroupAttrs is a more efficient version of [Group]
// that accepts only [Attr] values.
//
// This is an alias of https://pkg.go.dev/log/slog#GroupAttrs.
func GroupAttrs(key string, attrs ...Attr) Attr {
	return slog.GroupAttrs(key, attrs...)
}

// Any returns an Attr for the supplied value.
// See [AnyValue] for how values are treated.
//
// This is an alias of https://pkg.go.dev/log/slog#Any.
func Any(key string, value any) Attr {
	return slog.Any(key, value)
}

// NewJSONHandler creates a [JSONHandler] that writes to w,
// using the given options.
// If opts is nil, the default options are used.
//
// This is an alias of https://pkg.go.dev/log/slog#NewJSONHandler.
func NewJSONHandler(w io.Writer, opts *HandlerOptions) *JSONHandler {
	return slog.NewJSONHandler(w, opts)
}

// SetLogLoggerLevel controls the level for the bridge to the [log] package.
//
// Before [SetDefault] is called, slog top-level logging functions call the default [log.Logger].
// In that mode, SetLogLoggerLevel sets the minimum level for those calls.
// By default, the minimum level is Info, so calls to [Debug]
// (as well as top-level logging calls at lower levels)
// will not be passed to the log.Logger. After calling
//
//	slog.SetLogLoggerLevel(slog.LevelDebug)
//
// calls to [Debug] will be passed to the log.Logger.
//
// After [SetDefault] is called, calls to the default [log.Logger] are passed to the
// slog default handler. In that mode,
// SetLogLoggerLevel sets the level at which those calls are logged.
// That is, after calling
//
//	slog.SetLogLoggerLevel(slog.LevelDebug)
//
// A call to [log.Printf] will result in output at level [LevelDebug].
//
// SetLogLoggerLevel returns the previous value.
//
// This is an alias of https://pkg.go.dev/log/slog#SetLogLoggerLevel.
func SetLogLoggerLevel(level Level) (oldLevel Level) {
	return slog.SetLogLoggerLevel(level)
}

// Default returns the default [Logger].
//
// This is an alias of https://pkg.go.dev/log/slog#Default.
func Default() *Logger {
	return slog.Default()
}

// SetDefault makes l the default [Logger], which is used by
// the top-level functions [Info], [Debug] and so on.
// After this call, output from the log package's default Logger
// (as with [log.Print], etc.) will be logged using l's Handler,
// at a level controlled by [SetLogLoggerLevel].
//
// This is an alias of https://pkg.go.dev/log/slog#SetDefault.
func SetDefault(l *Logger) {
	slog.SetDefault(l)
}

// New creates a new Logger with the given non-nil Handler.
//
// This is an alias of https://pkg.go.dev/log/slog#New.
func New(h Handler) *Logger {
	return slog.New(h)
}

// With calls [Logger.With] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#With.
func With(args ...any) *Logger {
	return slog.With(args...)
}

// NewLogLogger returns a new [log.Logger] such that each call to its Output method
// dispatches a Record to the specified handler. The logger acts as a bridge from
// the older log API to newer structured logging handlers.
//
// This is an alias of https://pkg.go.dev/log/slog#NewLogLogger.
func NewLogLogger(h Handler, level Level) *log.Logger {
	return slog.NewLogLogger(h, level)
}

// Debug calls [Logger.Debug] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#Debug.
func Debug(msg string, args ...any) {
	slog.Debug(msg, args...)
}

// DebugContext calls [Logger.DebugContext] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#DebugContext.
func DebugContext(ctx context.Context, msg string, args ...any) {
	slog.DebugContext(ctx, msg, args...)
}

// Info calls [Logger.Info] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#Info.
func Info(msg string, args ...any) {
	slog.Info(msg, args...)
}

// InfoContext calls [Logger.InfoContext] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#InfoContext.
func InfoContext(ctx context.Context, msg string, args ...any) {
	slog.InfoContext(ctx, msg, args...)
}

// Warn calls [Logger.Warn] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#Warn.
func Warn(msg string, args ...any) {
	slog.Warn(msg, args...)
}

// WarnContext calls [Logger.WarnContext] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#WarnContext.
func WarnContext(ctx context.Context, msg string, args ...any) {
	slog.WarnContext(ctx, msg, args...)
}

// Error calls [Logger.Error] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#Error.
func Error(msg string, args ...any) {
	slog.Error(msg, args...)
}

// ErrorContext calls [Logger.ErrorContext] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#ErrorContext.
func ErrorContext(ctx context.Context, msg string, args ...any) {
	slog.ErrorContext(ctx, msg, args...)
}

// Log calls [Logger.Log] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#Log.
func Log(ctx context.Context, level Level, msg string, args ...any) {
	slog.Log(ctx, level, msg, args...)
}

// LogAttrs calls [Logger.LogAttrs] on the default logger.
//
// This is an alias of https://pkg.go.dev/log/slog#LogAttrs.
func LogAttrs(ctx context.Context, level Level, msg string, attrs ...Attr) {
	slog.LogAttrs(ctx, level, msg, attrs...)
}

// NewRecord creates a [Record] from the given arguments.
// Use [Record.AddAttrs] to add attributes to the Record.
//
// NewRecord is intended for logging APIs that want to support a [Handler] as
// a backend.
//
// This is an alias of https://pkg.go.dev/log/slog#NewRecord.
func NewRecord(t time.Time, level Level, msg string, pc uintptr) Record {
	return slog.NewRecord(t, level, msg, pc)
}

// NewTextHandler creates a [TextHandler] that writes to w,
// using the given options.
// If opts is nil, the default options are used.
//
// This is an alias of https://pkg.go.dev/log/slog#NewTextHandler.
func NewTextHandler(w io.Writer, opts *HandlerOptions) *TextHandler {
	return slog.NewTextHandler(w, opts)
}

// StringValue returns a new [Value] for a string.
//
// This is an alias of https://pkg.go.dev/log/slog#StringValue.
func StringValue(value string) Value {
	return slog.StringValue(value)
}

// IntValue returns a [Value] for an int.
//
// This is an alias of https://pkg.go.dev/log/slog#IntValue.
func IntValue(v int) Value {
	return slog.IntValue(v)
}

// Int64Value returns a [Value] for an int64.
//
// This is an alias of https://pkg.go.dev/log/slog#Int64Value.
func Int64Value(v int64) Value {
	return slog.Int64Value(v)
}

// Uint64Value returns a [Value] for a uint64.
//
// This is an alias of https://pkg.go.dev/log/slog#Uint64Value.
func Uint64Value(v uint64) Value {
	return slog.Uint64Value(v)
}

// Float64Value returns a [Value] for a floating-point number.
//
// This is an alias of https://pkg.go.dev/log/slog#Float64Value.
func Float64Value(v float64) Value {
	return slog.Float64Value(v)
}

// BoolValue returns a [Value] for a bool.
//
// This is an alias of https://pkg.go.dev/log/slog#BoolValue.
func BoolValue(v bool) Value {
	return slog.BoolValue(v)
}

// TimeValue returns a [Value] for a [time.Time].
// It discards the monotonic portion.
//
// This is an alias of https://pkg.go.dev/log/slog#TimeValue.
func TimeValue(v time.Time) Value {
	return slog.TimeValue(v)
}

// DurationValue returns a [Value] for a [time.Duration].
//
// This is an alias of https://pkg.go.dev/log/slog#DurationValue.
func DurationValue(v time.Duration) Value {
	return slog.DurationValue(v)
}

// GroupValue returns a new [Value] for a list of Attrs.
// The caller must not subsequently mutate the argument slice.
//
// This is an alias of https://pkg.go.dev/log/slog#GroupValue.
func GroupValue(as ...Attr) Value {
	return slog.GroupValue(as...)
}

// AnyValue returns a [Value] for the supplied value.
//
// If the supplied value is of type Value, it is returned
// unmodified.
//
// Given a value of one of Go's predeclared string, bool, or
// (non-complex) numeric types, AnyValue returns a Value of kind
// [KindString], [KindBool], [KindUint64], [KindInt64], or [KindFloat64].
// The width of the original numeric type is not preserved.
//
// Given a [time.Time] or [time.Duration] value, AnyValue returns a Value of kind
// [KindTime] or [KindDuration]. The monotonic time is not preserved.
//
// For nil, or values of all other types, including named types whose
// underlying type is numeric, AnyValue returns a value of kind [KindAny].
//
// This is an alias of https://pkg.go.dev/log/slog#AnyValue.
func AnyValue(v any) Value {
	return slog.AnyValue(v)
}
